// <auto-generated />
using System;
using AhorcadoBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AhorcadoBackend.Migrations
{
    [DbContext(typeof(JuegoDbContext))]
    partial class JuegoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("AhorcadoBackend.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasJugador")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FueVictoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PalabraSecreta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
